name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign users
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # configuration-path: .github/auto_assign.yml # Uncomment and create this file if you want custom config